# Generated by Django 5.1.6 on 2025-03-11 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('ARG', 'Argentina'), ('COL', 'Colombia'), ('MEX', 'Mexico'), ('ESP', 'España'), ('FRA', 'Francia')], max_length=100, null=True)),
            ],
        ),
    ]
